#include "header.h"

double SETUP_DATA_SKEW = 1.0;
double SETUP_BUDGET_RATIO = 0.1;
long SETUP_REPORT_PERIOD = 1;
long SETUP_FILE_BLOCKS = 64;
long SETUP_RANDOM_SEED = 0;
long SETUP_SCHEDULER_TYPE = FAIR_SCHEDULER;
long SETUP_MODE_TYPE = MODE_BASELINE;

void setup(void)
{

}